### PR TITLE
fix: Validate Create Sponsor and Create Track fields for just spaces without any text

### LINKED ISSUE #1433: Create Sponsor even allows blank spaces in name making the name empty
**Describe the bug**
Even a single space can be entered in the Sponsor Name and it will be accepted.

**To Reproduce**
1. Go to Sponsors
2. Click on the FAB to create a new sponsor.
3. Put just one or more spaces in the name field and try to submit.
4. It will be accepted.

**Expected behavior**
The spaces should be trimmed and error message should be displayed disallowing empty name field.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1433 and #1434 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes:

Now, submission of details will display error if user enters just spaces without any text in the fields of Create Sponsor and Create Track.

### CODE REVIEW

File: app/src/main/java/com/eventyay/organizer/core/sponsor/create/CreateSponsorFragment.java [hunk 1]
```diff
@@ -66,6 +66,11 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
         }
 
         binding.submit.setOnClickListener(view -> {
+
+            binding.form.name.setText(binding.form.name.getText().toString().trim());
+            binding.form.quantity.setText(binding.form.quantity.getText().toString().trim());
+            binding.form.price.setText(binding.form.price.getText().toString().trim());
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/sponsor/create/CreateSponsorFragment.java]: Just trim in the presenter/viewmodel

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/sponsor/create/CreateSponsorFragment.java]: But how can this be done since validation is being done through the fragment?

Comment (iamareebjamal) [reply app/src/main/java/com/eventyay/organizer/core/sponsor/create/CreateSponsorFragment.java]: Just add validateEmpty to the XML then

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/sponsor/create/CreateSponsorFragment.java]: It's already there but I think it doesn't consider the 'only spaces' case
