### PR TITLE
fix: order the tickets on tickets page

### LINKED ISSUE #365: Unordered tickets
tickets in the ticket list page are unordered. 

Screenshot:
screenshot_2017-07-26-19-42-37

Expected:
Tickets displayed should be in order. First, all paid then all free.

taking this up

### PR DESCRIPTION
**Pull request by mejariamol**
fixes #365 

screenshot_2017-07-26-23-55-10

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal please review

File: app/src/main/java/org/fossasia/openevent/app/module/tickets/TicketsFragment.java [hunk 1]
```diff
@@ -102,8 +103,9 @@ private void setupRecyclerView() {
 
         RecyclerView recyclerView = binding.ticketsRecyclerView;
         recyclerView.setLayoutManager(new LinearLayoutManager(context));
-        recyclerView.setAdapter(ticketsAdapter);
+        recyclerView.addItemDecoration(new DividerItemDecoration(context, DividerItemDecoration.VERTICAL));
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/module/tickets/TicketsFragment.java]: This was handled in create ticket PR

**Comment by mejariamol** [comment]
@iamareebjamal please review.
