### PR TITLE
fix: Pressing back pops from backstack

### LINKED ISSUE #885: Pressing back on edit organizer details exits activity
### Bug Report    

**Actual Behaviour**

When pressing back either via soft or hard button, the about event organizer is finished.

**Expected Behaviour**

The fragment should be popped from backstack instead.

**Would you like to work on the issue?**

No

### PR DESCRIPTION
**Pull request by sridharjajoo**
Fixes #885 

Changes:
The edit organizer info fragment was added to backstack and the onBackPressed( ) was overridden so that when the count of number of fragment in backstack is greater than one , then the fragment should pop from the backstack and if count is 0 , activity can be exited.

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/app/core/organizer/detail/OrganizerDetailActivity.java [hunk 1]
```diff
@@ -45,4 +45,19 @@ public boolean onOptionsItemSelected(MenuItem item) {
     public AndroidInjector<Fragment> supportFragmentInjector() {
         return dispatchingAndroidInjector;
     }
+
+    @Override
+    public void onBackPressed() {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/organizer/detail/OrganizerDetailActivity.java]: Look at the PR merged by @mishuvs

File: app/src/main/java/org/fossasia/openevent/app/core/organizer/detail/OrganizerDetailActivity.java [hunk 2]
```diff
@@ -45,4 +45,19 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+        handleBackPress();
+    }
+
+    private void handleBackPress() {
+
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/organizer/detail/OrganizerDetailActivity.java]: Store fragment manager in a global variable
