### PR TITLE
fix: Nullify Empty Fields in Sponsors

### LINKED ISSUE #1078: Nullify empty fields in Create Sponsor Fragment
### Bug Report    

**Actual Behaviour**

When a user type in some text in URL fields of Create Sponsor form, then delete the text and click on submit. The server sends HTTP 422 Unprocessable entity.

**Expected Behaviour**

The text input fields should get nullified on their own.

**Steps to reproduce it**

Type invalid text in Url fields of CreateSponsorFragment -> Delete it -> Exit the form.

**LogCat for the issue**

`HTTP 422 Unprocessable Entity`

**Android version and Phone Model**

Jelly Bean and Moto G4 Plus
    
**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Masquerade0097**
Fixes #1078 

Changes: 
1. Set Empty fields while Sponsors creation to null.
2. Set Empty fields while Sponsors update to null.

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/app/core/sponsor/create/CreateSponsorPresenter.java [hunk 1]
```diff
@@ -31,12 +32,19 @@ public Sponsor getSponsor() {
         return sponsor;
     }
 
+    protected void nullifyEmptyFields(Sponsor sponsor) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/sponsor/create/CreateSponsorPresenter.java]: Add VisibleForTesting

Comment (Masquerade0097) [reply app/src/main/java/org/fossasia/openevent/app/core/sponsor/create/CreateSponsorPresenter.java]: Added.
