### PR TITLE
fix: Improve Offline Support to the Attendee Check In

### LINKED ISSUE #450: Unclear attendee's checked in status if the toggle request is pending
To be done following the commit from PR #448 

Currently when in case of network issue the attendee check in toggle request is added to the jobs queue, the check in status of the attendee cannot determined in the mean time until the job is done. 

Expected: 
1. A local attendee's check in status must be shown to the user. 
2. Show if an attendee is synced with the server.

taking this up.

### PR DESCRIPTION
**Pull request by mejariamol**
- Modified scheduleToggle method to update the attendee locally first before adding the job to the queue.
- Added ticks icon to the attendee layout and bottom sheet layout to show if the attendee is in sync with the server.
- Modified check in status icon in the attendee layout
- Modified attendee bottom sheet layout behavior for the above changes.

fixes #450

img_20170812_024148_533

screenshot_2017-08-12-15-31-20

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal please review and test on a device.
Will modify the unit tests finally.

File: app/src/main/java/org/fossasia/openevent/app/common/data/repository/AttendeeRepository.java [hunk 1]
```diff
@@ -114,14 +115,14 @@ public Completable scheduleToggle(Attendee attendee) {
                 attendee.setTicket(null);
                 attendee.setOrder(null);
 
-                attendee.setCheckedIn(!attendee.isCheckedIn());
-
                 return eventService.patchAttendee(attendee.getId(), attendee);
             })
-            .doOnNext(attendee ->
+            .doOnNext(attendee -> {
+                attendee.checking.set(false);
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/common/data/repository/AttendeeRepository.java]: This isn't needed. It'll automatically be false

File: app/src/main/res/layout/bottomsheet_attendee_check_in.xml [hunk 2]
```diff
@@ -157,15 +158,6 @@
                 app:srcCompat="@{ checkinAttendee.isCheckedIn ? @drawable/ic_checkout : @drawable/ic_checkin }"
                 app:tint="@android:color/white" />
 
-            <ProgressBar
```
Comment (iamareebjamal) [inline app/src/main/res/layout/bottomsheet_attendee_check_in.xml]: We can let this be, I think

Comment (mejariamol) [inline app/src/main/res/layout/bottomsheet_attendee_check_in.xml]: We  are letting the user to toggle the check in status again even if already job is pending. So here no need of progressbar. Also we are showing single/double tick in attendee layout to show sync status. So this progressbar not required.

Comment (iamareebjamal) [inline app/src/main/res/layout/bottomsheet_attendee_check_in.xml]: Show that in detail layout as well

Comment (mejariamol) [inline app/src/main/res/layout/bottomsheet_attendee_check_in.xml]: Yeah.

Comment (mejariamol) [inline app/src/main/res/layout/bottomsheet_attendee_check_in.xml]: screenshot_2017-08-12-14-37-02

**Comment by mejariamol** [comment]
@iamareebjamal please review.

File: app/src/main/res/layout/bottomsheet_attendee_check_in.xml (hunk 2 above)
Comment (iamareebjamal) [inline app/src/main/res/layout/bottomsheet_attendee_check_in.xml]: The checks should be center aligned

Comment (mejariamol) [inline app/src/main/res/layout/bottomsheet_attendee_check_in.xml]: in attendee item layout too?

Comment (mejariamol) [inline app/src/main/res/layout/bottomsheet_attendee_check_in.xml]: screenshot_2017-08-12-15-31-20

**Comment by mejariamol** [comment]
@iamareebjamal please review.

File: app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java [hunk 3]
```diff
@@ -124,7 +125,7 @@ public void shouldHandleAttendeeChange() {
         notifier.onNext(new DatabaseChangeListener.ModelChange<>(toggled, BaseModel.Action.UPDATE));
 
         verify(attendeeCheckInView).showResult(toggled);
-        verify(attendeeCheckInView).onSuccess(any());
+        verify(attendeeCheckInView, atLeast(2)).onSuccess(any());
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java]: Why is it getting triggered twice?

Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java]: Once when locally attendee is updated and once when network responds on successful toggle

Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java]: I think show success not required on attedee bottom sheet any more now. Shall i remove it?

Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java]: Yes :+1:

**Comment by mejariamol** [comment]
@iamareebjamal please review.

File: app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java (hunk 3 above)
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java]: The problem remains. This should not be called twice

Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java]: in onSuccess the `checkinAttendee` binding property is notified for change. So it will be called more than once.

Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java]: But why will it be called twice on a single change?

Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java]: Ok, I guess this can be taken in another PR

Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java]: >But why will it be called twice on a single change?

not single
1. first checking is set to true and checkedIn is toggled
2. and then checking is reset to false.
