### PR TITLE
fix: clearing database on different user login

### LINKED ISSUE #252: local data is not cleared on different user login
Currently we are matching username (email id) of new user to decide if local data is to be removed.

But as we are using (and shall be using) separate server for _dev_ branch where email can be same hence previous data stored is not removed in that case.

Expected: username and userid both shall be checked to decide previous data removal.

@iamareebjamal what is your opinion?

### PR DESCRIPTION
**Pull request by mejariamol**
- method `LoginModel::login` is modified to just get access token
- new method `LoginModel::isPreviousUser` is added to check different user login
- method `LoginPresenter::login` is modified accordingly to clear database on different user login and starts data loading after that only.

fixes #252

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal please test on device and review. Will be adding test later.

File: app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java [hunk 1]
```diff
@@ -43,18 +48,20 @@ public LoginModel(IUtilModel utilModel, EventService eventService, IDatabaseRepo
...
-                            .subscribe()
-                    ));
+                .observeOn(AndroidSchedulers.mainThread());
+    }
+
+    @Override
+    public Observable<Boolean> isPreviousUser() {
+        return Observable.combineLatest(eventService.getUser(getAuthorization()),
+            databaseRepository.getAllItems(User.class).switchIfEmpty(Observable.just(new User(""))).firstElement().toObservable(), this::areSameUsers)
+            .subscribeOn(Schedulers.io())
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: Why fetching the user from EventService here. It should be loaded at login itself. I mean to say that presenter should not trigger the logic to handle the previous user. Only LoginModel should do it. The presenter should only get the login success or error

File: app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java [hunk 2]
```diff
@@ -43,18 +48,20 @@ public LoginModel(IUtilModel utilModel, EventService eventService, IDatabaseRepo
...
+            .observeOn(AndroidSchedulers.mainThread());
+    }
+
+    private Boolean areSameUsers(User user1, User user2) {
+        return (user1.getId() == user2.getId() && user1.getEmail().equals(user2.getEmail()));
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: Override equals in User class instead

File: app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java (hunk 1 above)
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: Also, instead of using combineLatest with switchIfEmpty. First check if the database entry of users is empty and if it is, then no need to apply check at all. If it is not, then apply chaining logic

Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: @iamareebjamal Yeah. Initially I tried doing all the stuff in login itself but I couldn't manage synchronisation between database deletion -> actual login( starting MainActivity) . Please suggest an approach.

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: OK. Will do soon :+1:

Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: @iamareebjamal hey I think it would better to keep them separate. `LoginModel::login` should just handle login ie getting access token. Then before starting main activity it is presenter's work to check for data consistency and take actions accordingly. So I think current approach is fine. What do you say? doing all the stuff in the login itself will increase complexity.

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: The thing is presenter should never have access to db, it's not presenter's work. That's what models are there for. Presenter's job is to only get information from the model, without caring from where it is getting from, and process it to display it to view. All actions taken on data are the work of model

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: Models are actually the most complex part of MVP, as they are self-managed, they don't need input from presenter to trigger something

**Comment by mejariamol** [comment]
@iamareebjamal please review this.

**Comment by iamareebjamal** [comment]
@mejariamol There are no changes from the last time I reviewed it

**Comment by mejariamol** [comment]
>@iamareebjamal Yeah. Initially I tried doing all the stuff in login itself but I couldn't manage synchronisation between database deletion -> actual login( starting MainActivity) . Please suggest an approach.

>OK. Will do soon :+1:

I thought you were going to suggest another approach.

File: app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java (hunk 1 above)
Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: thing is that login view should start main activity only after completion of database handling. These two processes should be in sequence not concurrently.

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: This will be done in sequence only

Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: but if database handling is done in onNext and a user is returned to the login presenter where it will start main activity as it gets the user.

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: Let me try it

**Comment by iamareebjamal** [comment]
@mejariamol Please check and rewrite tests

File: app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java [hunk 3]
```diff
@@ -1,67 +1,81 @@
...
             .subscribeOn(Schedulers.io())
             .observeOn(AndroidSchedulers.mainThread());
     }
 
-    private Boolean areSameUsers(User user1, User user2) {
-        return (user1.getId() == user2.getId() && user1.getEmail().equals(user2.getEmail()));
+    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
+    public Single<Boolean> isPreviousUser() {
+        return databaseRepository.getAllItems(User.class)
+            .first(EMPTY)
```
Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: was this suppose to be `firstOrDefault` ? @iamareebjamal

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java]: No

**Comment by mejariamol** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
@mejariamol I must be really out of mind to forget that identity of the user is present in JWT token. Fix the tests, we'll merge this and I'll add parsing code and tests and send a separate PR

**Comment by mejariamol** [comment]
@iamareebjamal please review. :+1:

**Comment by iamareebjamal** [comment]
@Shailesh351 @arp95 @shreyasnbhat @rohanagarwal94 Please review
