### PR TITLE
fix: implement field validation for Event Creation Stepper-Step 1

### LINKED ISSUE #1271: Stepper allows moving to next steps even when Step 1 fields are invalid
**Is it a ?**

- [x] Bug Report

### Bug Report    

**Actual Behaviour**
When creating event, the `Next` button takes to Step 2 even when Step 1 fields are invalid. Then in Step 3, after clicking `Create` button it shows the error for fields in Step 1.

**Expected Behaviour**

It should show error in Step 1 itself, and shouldn't allow moving to next Steps.

**Steps to reproduce it**
1. When creating event, leave Event name empty or the dates same.
2. Stepper will allow going till step 3 and shows error on clicking `Create`.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mishuvs**
Fixes #1271 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: Verifies required fields in step 1 in step 1 only, and not after step 3.

### CODE REVIEW

File: app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventViewModel.java [hunk 1]
```diff
@@ -94,8 +94,8 @@ public Event getEvent() {
         return eventMutableLiveData;
     }
 
-    private boolean verify() {
-        if (event.getName() == null) {
+    public boolean verify() {
+        if (event.getName() == null || event.getName().isEmpty()) {
```
Comment (Masquerade0097) [inline app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventViewModel.java]: Utils.isEmpty

**Comment by Masquerade0097** [comment]
Use [Commit guidelines](https://chris.beams.io/posts/git-commit/) for a proper commit
