### PR TITLE
Fix bug: Pressing back on create/edit copyright exits activity #884

### LINKED ISSUE #884: Pressing back on create/edit copyright exits activity
### Bug Report    

**Actual Behaviour**

When pressing back either via soft or hard button, the about event activity is finished.

**Expected Behaviour**

The fragment should be popped from backstack instead.

**Would you like to work on the issue?**

No

### PR DESCRIPTION
**Pull request by mishuvs**
Fixes #884 

Changes: 
    1. Add Copyright Fragment to backstack
    2. Change activity's home action to `finish()` only when there's no fragment in backstack

Screenshots of the change: 
backstackcopyright

### CODE REVIEW

**Comment by mishuvs** [comment]
@iamareebjamal Please review.

File: app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java [hunk 1]
```diff
@@ -37,7 +37,10 @@ protected void onCreate(Bundle savedInstanceState) {
     public boolean onOptionsItemSelected(MenuItem item) {
         switch (item.getItemId()) {
             case android.R.id.home:
-                finish();
+                if (getSupportFragmentManager().getBackStackEntryCount() > 0)
+                    getSupportFragmentManager().popBackStack();
+                else
+                    finish();
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java]: Clicking on hardware back button should work as well

File: app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java [hunk 2]
```diff
@@ -125,11 +125,13 @@ public boolean onOptionsItemSelected(MenuItem item) {
             case R.id.action_create_change_copyright:
                 if (creatingCopyright) {
                     getFragmentManager().beginTransaction()
-                        .replace(R.id.fragment, CreateCopyrightFragment.newInstance())
+                        .add(R.id.fragment, CreateCopyrightFragment.newInstance())
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java]: Don't use add

File: app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java (hunk 1 above)
Comment (mishuvs) [reply app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java]: It does. Since the fragment is added to backstack, clicking phone's back button works as well by reversing the transition.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java]: OK, use a shared variable for FragmentManager

File: app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java (hunk 2 above)
Comment (mishuvs) [reply app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java]: Using `#add` will retain AboutEventFragment's state. So on back-press, no progress bar will be shown, making it look smooth. The newly created copyright is added instantly to event details without a progress bar. What do you think?

File: app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java (hunk 1 above)
Comment (mishuvs) [reply app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java]: Umm, it's used only once. Why use a shared variable?

File: app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java (hunk 2 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java]: It takes more memory but alright, we'll switch to add if there are more fragments

Comment (mishuvs) [reply app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java]: Is that a yes or do we add `add` later?
