### PR TITLE
fix: Remove warnings and organize code, XML and variable names

### LINKED ISSUE #90: Fix project wide lint warnings
There are several lint warnings in the project and some style issues.

We should fix them before adding any features.

### PR DESCRIPTION
**Pull request by iamareebjamal**
[WIP] Fixes #90 

- Remove lint warning
- Organize code and XML
- Remove unused attributes and variables
- Change naming convention to standard Java convention : 
    - Package names are all lowercase
    - No use of Hungarian Notation
    - Constants are all caps

### CODE REVIEW

**Comment by iamareebjamal** [comment]
App is not crashing my side

But if anyone with sufficient test data can test the application, it'd be great

Thanks

**Comment by iamareebjamal** [comment]
@Ronak-59 @Rishabhk07 @mejariamol Please test the apk and tell if there are any issues

We really need to set up the basic project architecture into something maintainable and testable before we move in to add features into it

I think we should be able to set up basic MVP architecture till Milestone 1, that is May 14

File: app/src/main/java/org/fossasia/openevent/app/MainActivity.java [hunk 1]
```diff
@@ -1,16 +0,0 @@
-package org.fossasia.openevent.app;
-
-import android.app.Application;
-import android.content.Context;
-import android.content.SharedPreferences;
-
-import org.fossasia.openevent.app.Utils.Constants;
```
Comment (Ronak-59) [inline app/src/main/java/org/fossasia/openevent/app/MainActivity.java]: please change "Utils" to "utils"

File: app/src/main/java/org/fossasia/openevent/app/getApplication.java [hunk 2]
```diff
@@ -1,23 +0,0 @@
-package org.fossasia.openevent.app;
-
-import android.app.Application;
-import android.content.Context;
-import android.content.SharedPreferences;
-
-import org.fossasia.openevent.app.Utils.Constants;
```
Comment (Ronak-59) [inline app/src/main/java/org/fossasia/openevent/app/getApplication.java]: please change "Utils" to "utils"

File: app/src/main/java/org/fossasia/openevent/app/MainActivity.java (hunk 1 above)
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/MainActivity.java]: You are viewing old files :stuck_out_tongue:

File: app/src/main/java/org/fossasia/openevent/app/getApplication.java (hunk 2 above)
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/getApplication.java]: Same as above

Please test apk

File: app/src/main/java/org/fossasia/openevent/app/getApplication.java [hunk 3]
```diff
@@ -1,23 +0,0 @@
...
-
-public class getApplication extends Application {
-
-    @Override
-    public void onCreate() {
-        super.onCreate();
-    }
-
-    public String getToken(){
-        SharedPreferences sharedPreferences = getSharedPreferences(Constants.fossPrefs, Context.MODE_PRIVATE);
```
Comment (Ronak-59) [inline app/src/main/java/org/fossasia/openevent/app/getApplication.java]: please change "Constants.fossPrefs" to "Constants.FOSS_PREFS" and "Constants.sharedPrefsToken" to "Constants.SHARED_PREFS_TOKEN"

File: app/src/main/java/org/fossasia/openevent/app/MainActivity.java [hunk 4]
```diff
@@ -1,16 +0,0 @@
...
-
-public class MainActivity extends Application {
-
-    public String getToken(){
-        SharedPreferences sharedPreferences = getSharedPreferences(Constants.fossPrefs, Context.MODE_PRIVATE);
-        String token = sharedPreferences.getString(Constants.sharedPrefsToken,"null");
```
Comment (Ronak-59) [inline app/src/main/java/org/fossasia/openevent/app/MainActivity.java]: please change "Constants.fossPrefs" to "Constants.FOSS_PREFS" and "Constants.sharedPrefsToken" to "Constants.SHARED_PREFS_TOKEN"

File: app/src/main/java/org/fossasia/openevent/app/getApplication.java (hunk 3 above)
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/getApplication.java]: Old files again. Please look at the right section

File: app/src/main/java/org/fossasia/openevent/app/MainActivity.java (hunk 1 above)
Comment (Ronak-59) [inline app/src/main/java/org/fossasia/openevent/app/MainActivity.java]: Oh! wait.. got a bit confused

File: app/src/main/java/org/fossasia/openevent/app/MainActivity.java (hunk 4 above)
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/MainActivity.java]: Please look at new changes. You are reviewing old files

File: app/src/main/res/layout/activity_event_details.xml [hunk 5]
```diff
@@ -1,171 +1,177 @@
...
         <TextView
+            android:id="@+id/editText3"
             android:layout_width="wrap_content"
             android:layout_height="wrap_content"
-            android:text="0"
-            android:textAppearance="@style/TextAppearance.AppCompat.Small"
-            android:id="@+id/tvTicketSold" />
+            android:layout_margin="10dp"
+            android:paddingBottom="0dp"
+            android:paddingLeft="12dp"
```
Comment (mejariamol) [inline app/src/main/res/layout/activity_event_details.xml]: @iamareebjamal use `R.dimen` for such values, so that it will be easy in future if it needs to changed . For example `R.dimen.padding_side`. Store dimension values in `res/`

File: app/src/main/java/org/fossasia/openevent/app/model/UserEvents.java [hunk 6]
```diff
@@ -1,353 +1,350 @@
...
 package org.fossasia.openevent.app.model;
 
-import java.util.List;
-
 import com.google.gson.annotations.SerializedName;
 
-
+import java.util.List;
 
 public class UserEvents {
```
Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/model/UserEvents.java]: @iamareebjamal What exactly `UserEvents` is ? I couldn't get why it is plural ?

File: app/src/main/java/org/fossasia/openevent/app/model/LicenseDetails.java [hunk 7]
```diff
@@ -1,72 +1,68 @@
-
 package org.fossasia.openevent.app.model;
 
-
 import com.google.gson.annotations.SerializedName;
 
-
-
-public class LicenceDetails {
+public class LicenseDetails {
```
Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/model/LicenseDetails.java]: @iamareebjamal just `License` is better. Since it is class.

File: app/src/main/java/org/fossasia/openevent/app/model/EventDetails.java [hunk 8]
```diff
@@ -1,362 +1,360 @@
...
 package org.fossasia.openevent.app.model;
 
-import java.util.List;
-
 import com.google.gson.annotations.SerializedName;
 
-@SuppressWarnings("unused")
+import java.util.List;
+
 public class EventDetails {
```
Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/model/EventDetails.java]: @iamareebjamal `Event` would be better.

**Comment by Ronak-59** [comment]
Sorry for checking out old files. I tested new files as per @iamareebjamal 's pull request. Got an App crash. Please check the error log : https://hastebin.com/itutibaney.nginx

File: app/src/main/java/org/fossasia/openevent/app/adapters/AttendeeListAdapter.java [hunk 9]
```diff
@@ -15,59 +15,60 @@
...
 public class AttendeeListAdapter extends RecyclerView.Adapter<AttendeeListAdapter.AttendeeListAdapterHolder> {
-    ArrayList<Attendee> attendeeDetailses;
-    Activity activity;
-    long id;
-    public static final String TAG = "AttendeeAdapter";
-
-    public AttendeeListAdapter(ArrayList<Attendee> attendeeDetailses, Activity activity, long id) {
-        this.attendeeDetailses = attendeeDetailses;
-        this.activity = activity;
+    private List<Attendee> attendeeDetails;
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/adapters/AttendeeListAdapter.java]: True

File: app/src/main/java/org/fossasia/openevent/app/model/EventDetails.java [hunk 10]
```diff
@@ -1,362 +1,360 @@
...
-        return mDescription;
+        return description;
     }
 
     public void setDescription(String description) {
-        mDescription = description;
+        this.description = description;
     }
 
     public Object getEmail() {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/model/EventDetails.java]: That's a bug in JSPNSchema2POJO which was originally in the code, I replaced it almost everywhere, this one I must have forgot. Thanks

File: app/src/main/java/org/fossasia/openevent/app/model/UserEvents.java (hunk 6 above)
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/model/UserEvents.java]: Again. Due to original code. Fixing

**Comment by iamareebjamal** [comment]
@Ronak-59 Thanks. Taking a look

File: app/src/main/res/layout/activity_event_details.xml (hunk 5 above)
Comment (iamareebjamal) [inline app/src/main/res/layout/activity_event_details.xml]: That could be taken up in a separate issue as this PR is large enough

**Comment by iamareebjamal** [comment]
@Ronak-59 When did the crash occur?

**Comment by iamareebjamal** [comment]
Should be fixed now. Please test

**Comment by Ronak-59** [comment]
@iamareebjamal as soon as i clicked on event name, the layout showing progress bar, etc opened and within 2 seconds, it crashed

**Comment by Ronak-59** [comment]
Alright, testing...

File: app/src/main/java/org/fossasia/openevent/app/adapters/EventListAdapter.java [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+
+        return new EventRecyclerViewHolder(itemView);
+    }
+
+    @Override
+    public void onBindViewHolder(final EventRecyclerViewHolder holder, int position) {
+
+        final Event thisEvent = events.get(position);
+        holder.eventTitle.setText(thisEvent.getName());
+        Picasso.with(context).load(thisEvent.getThumbnail()).into(holder.eventImage);
```
Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/adapters/EventListAdapter.java]: @iamareebjamal here if `thisEvent.getThumbnail()` is empty, it throws exception. Put such blocks in try-catch

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/adapters/EventListAdapter.java]: This PR is actually just fixing lint errors and naming, if we continue developing on this PR, we won't move forward. Our motive should be to make this PR mergable so there are no crashes and then start fixing bugs in other issues

Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/adapters/EventListAdapter.java]: @iamareebjamal yes you are right. But the app is getting crashed due to that exception.

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/adapters/EventListAdapter.java]: OK :+1:

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/adapters/EventListAdapter.java]: Although it's quite strange that the original app wasn't crashing

**Comment by iamareebjamal** [comment]
@mejariamol Please test now

**Comment by iamareebjamal** [comment]
I have also fixed some other issues and test few components myself. If someone else could test the app, we can finally merge it and move towards MVP implementation

@mejariamol @Ronak-59

**Comment by Ronak-59** [comment]
Awesome @iamareebjamal , testing...

**Comment by Ronak-59** [comment]
@mejariamol @iamareebjamal @niranjan94 Tested this latest code by @iamareebjamal and encountered no app-crash or major bugs. According to me, we should merge this PR so that we can finally work on the UI and functionalities.
