### PR TITLE
bug:Added validation to edit text fields

### LINKED ISSUE #950: Bug while entering URL in Create Sponsors Fragment
### Bug Report    

**Actual Behaviour**
While a sponsor is being created and the URL Is being entered then there should be a check simultaneously that whether the URL is being entered is correct or not in correct format or not.

 **Expected Behaviour**
There should be validation while a URL is being entered.
 
@iamareebjamal I would like to work on it

### PR DESCRIPTION
**Pull request by sridharjajoo**
Fixes #950 

Screenshots for the change: 
whatsapp image 2018-05-17 at 00 01 44 1

### CODE REVIEW

**Comment by sridharjajoo** [comment]
@iamareebjamal Kindly review

File: app/src/main/java/org/fossasia/openevent/app/core/sponsor/create/CreateSponsorView.java [hunk 1]
```diff
@@ -8,4 +11,5 @@
 
     void dismiss();
 
+    void validate(TextInputLayout textInputLayout, Function<String, Boolean> function, String str);
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/sponsor/create/CreateSponsorView.java]: Why is there a need to add this?

Comment (sridharjajoo) [reply app/src/main/java/org/fossasia/openevent/app/core/sponsor/create/CreateSponsorView.java]: Sorry ,not needed. I'll remove it from interface and add a simple method
