### PR TITLE
fix: Scan QR fab visibility

### LINKED ISSUE #238: Scan button behaviour
- Hide Scan button on scroll
- Only show scan button if there are attendees

### PR DESCRIPTION
**Pull request by mejariamol**
- Hides on scroll
- Hides on empty page

fixes #238

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal @Shailesh351 @arp95 @rohanagarwal94 please review.

File: app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java [hunk 1]
```diff
@@ -178,6 +178,18 @@ public void onChanged() {
             }
         };
         stickyHeaderAdapter.registerAdapterDataObserver(adapterDataObserver);
+
+        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java]: This may get used in many upcoming fragments/activities. Please add a static method in ViewUtils with RecyclerView and FAB as argument

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java]: Also, remove listener in onDestroy

File: app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesPresenter.java [hunk 2]
```diff
@@ -99,11 +99,12 @@ public void loadAttendees(boolean forceReload) {
                 if (attendeesView == null) return;
                 attendeesView.showAttendees(attendees);
                 hideProgress(forceReload);
-                attendeesView.showScanButton(true);
+                attendeesView.showScanButton(attendeeList.size() != 0);
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesPresenter.java]: Use !attendeeList.isEmpty()

File: app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java [hunk 3]
```diff
@@ -227,6 +280,22 @@ public void shouldNotShowEmptyViewOnSwipeRefreshSuccess() {
...
+
+        InOrder inOrder = Mockito.inOrder(eventRepository, attendeesView);
+
+        attendeesPresenter.loadAttendees(true);
+
+        inOrder.verify(attendeesView).showScanButton(false);
+        inOrder.verify(eventRepository).getAttendees(id, true);
+        inOrder.verify(attendeesView).showAttendees(attendees);
+        inOrder.verify(attendeesView).onRefreshComplete();
+        inOrder.verify(attendeesView).showScanButton(true);
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java]: This was a mistake I made in past. Please only verify that scan button is shown. Tests should not overlap. Do it with the other tests you added as well. Nice job!

File: app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java (hunk 1 above)
Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java]: > remove listener in onDestroy

Actually I left it intentionally. I didn't understand the need of removing listener in `onDestroy`, since anyway after `onDestroy` recyclerView will be destroyed. Hence no need to save the listener separately and destroy it in `onDestroy` call. Better pass it directly to the recyclerView.

what do you say?

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java]: True. The recyclerview will destroy. No need

File: app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java (hunk 3 above)
Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java]: done. :+1:
