### PR TITLE
fix: Prevent empty view layout from showing when items are present

### LINKED ISSUE #1722: Empty view layout shows even when items are displayed
**Describe the bug**
Empty view layout also shows along with items.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1722

### CODE REVIEW

File: app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java [hunk 1]
```diff
@@ -237,9 +237,11 @@ public void showMessage(String message) {
 
     @Override
     public void showResults(List<Faq> items) {
-        if(items.isEmpty()) {
+        if (items.isEmpty()) {
             showEmptyView(true);
             return;
+        } else {
+            showEmptyView(false);
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java]: Move this out of if condition and change to `showEmptyView(items.isEmpty());`

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java]: Done.
