### PR TITLE
Issue App crashing on Opening in Android Oreo 8.1 #1356

### LINKED ISSUE #1356: App crashing on Opening in Android Oreo 8.1
**Describe the bug**
When the app is run phones having Android Oreo, the app crashes.

**To Reproduce**
1. Open app in Oreo

**Expected behavior**
App shouldn't crash.

**Smartphone Info:**
|Device| Mi A2|
|Android Version| Oreo 8.1  |

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by Vanethos**
Fixes #1356 

After reading through some articles, I have found out that using strict policy on certain devices will cause a DiskReadViolation that may not be related to the app's code, but due to an external library or each hardware maker's specific software.

By outting " .permitDiskReads()" we can avert this situation. In the comment there is a link to an article where this is explained in detail.

Checklist:

- [X] I have checked for PMD and check-style issues 
- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream development branch.

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Thank you for the PR. Please follow the PR template and mention the issue number in the fixes section and also list the changes performed

**Comment by iamareebjamal** [comment]
Also, please only permit the disk reads for Oreo and above

**Comment by Vanethos** [comment]
@iamareebjamal 
I am deeply sorry, since I am new to the open-source community, I didn't read the correct guidelines.

I am going to fix this and send another PR, thanks!

**Comment by iamareebjamal** [comment]
No need for sending another PR, you can edit this one

**Comment by Vanethos** [comment]
I think I did that just now!

By pulling a commit it will update this PR, correct? (sorry for the noob questions..)

File: app/src/main/java/com/eventyay/organizer/OrgaApplication.java [hunk 1]
```diff
@@ -86,11 +87,20 @@ public void onCreate() {
...
-            StrictMode.setThreadPolicy(
-                new StrictMode.ThreadPolicy.Builder()
-                    .detectAll()
-                    .penaltyDeath()
-                    .build());
+            StrictMode.ThreadPolicy.Builder policyBuilder = new StrictMode.ThreadPolicy.Builder()
+                .detectAll()
+                .penaltyDeath();
+
+            if (android.os.Build.VERSION.SDK_INT > Build.VERSION_CODES.O) {
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/OrgaApplication.java]: This should be >=

And why fully qualified class name for Build?

Comment (Vanethos) [reply app/src/main/java/com/eventyay/organizer/OrgaApplication.java]: You are correct, my mistake, on it.

**Comment by iamareebjamal** [comment]
Great, now please update the PR description following the template

**Comment by Vanethos** [comment]
Will do!

**Comment by Vanethos** [comment]
From what I read, I had to update the description to have the "resolve" keyword and check the correct checkboxes, right?

**Comment by Vanethos** [comment]
Changed! Sorry for all the inconvenience
