### PR TITLE
bug: fix PMD and Checkstyle Issues

### LINKED ISSUE #988: Fix PMD and Checkstyle Issues
https://584-65606855-gh.circle-artifacts.com/0/outputs/pmd/pmd.html
https://584-65606855-gh.circle-artifacts.com/0/outputs/checkstyle/checkstyle.html

@mishuvs @srv-twry @Masquerade0097 @sridharjajoo Please take a look

### PR DESCRIPTION
**Pull request by mishuvs**
Fixes #988 

Changes: Fixes most PMD and CheckStyle violations, and suppresses other inevitable warnings.

Facing problem: In MainPresenter, the SuppressWarning annotation about more than 7 parameters being used, is not working. Also tried making changes to checkstyle.xml

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java [hunk 1]
```diff
@@ -77,6 +77,7 @@ public void onStart() {
         binding.forgotPasswordLink.setOnClickListener(view -> openForgotPasswordPage());
     }
 
+    @SuppressWarnings("unused")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java]: If it is unused, either use it or remove it

File: app/src/main/java/org/fossasia/openevent/app/core/faq/list/viewholder/FaqViewHolder.java [hunk 2]
```diff
@@ -14,7 +14,7 @@
 
     private final FaqLayoutBinding binding;
     private Faq faq;
-    private FaqListPresenter faqListPresenter;
+    private final FaqListPresenter faqListPresenter;
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/faq/list/viewholder/FaqViewHolder.java]: Move final fields together and add a newline

File: app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/viewholder/SponsorsViewHolder.java [hunk 3]
```diff
@@ -12,7 +12,7 @@
 
     private final SponsorItemBinding binding;
     private Sponsor sponsor;
-    private SponsorsPresenter sponsorsPresenter;
+    private final SponsorsPresenter sponsorsPresenter;
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/viewholder/SponsorsViewHolder.java]: move

File: app/src/main/java/org/fossasia/openevent/app/core/track/list/viewholder/TracksViewHolder.java [hunk 4]
```diff
@@ -10,7 +10,7 @@
 public class TracksViewHolder extends RecyclerView.ViewHolder {
     private final TrackItemBinding binding;
     private Track track;
-    private TracksPresenter tracksPresenter;
+    private final TracksPresenter tracksPresenter;
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/track/list/viewholder/TracksViewHolder.java]: move

**Comment by iamareebjamal** [comment]
You made a function abstract, it shouldn't be

**Comment by mishuvs** [comment]
@iamareebjamal The warning about 8 parameters in MainPresenter for checkstyle seems to not be suppressed. What could be done?

File: app/src/main/java/org/fossasia/openevent/app/common/mvp/view/BaseFragment.java [hunk 5]
```diff
@@ -20,13 +20,15 @@ public void onResume() {
         setTitle(getString(getTitle()));
     }
 
+    @SuppressWarnings("PMD")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/common/mvp/view/BaseFragment.java]: Use fine grained suppressing

File: app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java [hunk 6]
```diff
@@ -57,7 +57,12 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
     public void onStart() {
         super.onStart();
 
-        loginFragmentViewModel.getLoginStatus().observe(this, this::handleIntent);
+        loginFragmentViewModel.getLoginStatus().observe(this, (loginStatus) -> {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java]: Revert as previous behaviour was desirable

**Comment by iamareebjamal** [comment]
@mishuvs The suppress tag you are using is not probably correct for checkstyle

File: app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java (hunk 6 above)
Comment (mishuvs) [reply app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java]: We'd then have to use the `handleIntent()` method which takes an unused boolean parameter, and we'll have to suppress its PMD warning it using `"unused" parameter`.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java]: Remove the boolean param from there

**Comment by mishuvs** [comment]
I think `@SuppressWarnings("checkstyle:parameternumber")` is the correct tag. [1](https://github.com/jshiell/checkstyle-idea/issues/108)
Setting "max" attribute to 8 solves the problem, but is probably not desired.

File: app/src/main/java/org/fossasia/openevent/app/core/main/MainPresenter.java [hunk 7]
```diff
@@ -41,7 +41,7 @@
     private User organizer;
 
     @Inject
-    @SuppressWarnings({"checkstyle:parameternumber"})
+    @SuppressWarnings("checkstyle:parameternumber")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/core/main/MainPresenter.java]: Try `@SuppressWarnings("ParameterNumber")` or

`//CHECKSTYLE:OFF: ParameterNumber`

Comment (mishuvs) [reply app/src/main/java/org/fossasia/openevent/app/core/main/MainPresenter.java]: Neither works

File: app/src/main/java/org/fossasia/openevent/app/common/mvp/view/BaseFragment.java (hunk 5 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/app/common/mvp/view/BaseFragment.java]: Fix this

File: app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java (hunk 6 above)
Comment (mishuvs) [reply app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java]: The method `handleIntent()` referenced by the observer needs to have the Boolean parameter because it's observing LiveData<Boolean>. I get error if I remove it.
screenshot from 2018-06-01 07-31-32
