### PR TITLE
fix: Make timezone preference reactive

### LINKED ISSUE #468: Fix date preference change reactivity
Currently, saved preference for the reactivity is not followed on start and changing the values also only invalidates non-static calls on the date string, that too only after Settings view is opened. 

Working on it

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #468 

- Move preference change observable to MainActivity
- Add invalidation code for MainActivity dates

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@mejariamol Please review

File: app/src/main/java/org/fossasia/openevent/app/module/settings/SettingsFragment.java [hunk 1]
```diff
@@ -39,21 +29,7 @@ public void onCreatePreferencesFix(@Nullable Bundle bundle, String rootKey) {
...
-            view.setBackgroundColor(ContextCompat.getColor(getActivity(), R.color.color_bottom_surface));
-        }
-
-        sharedPreferences.getBoolean(Constants.SHARED_PREFS_LOCAL_DATE)
-            .asObservable()
-            .distinctUntilChanged()
-            .subscribe(DateUtils::setShowLocal);
-
-        return view;
+        return super.onCreateView(inflater, container, savedInstanceState);
```
Comment (mejariamol) [inline app/src/main/java/org/fossasia/openevent/app/module/settings/SettingsFragment.java]: shall be removed if not overriding.

**Comment by iamareebjamal** [comment]
@mejariamol Please review now
