### PR TITLE
fix: disable background clicks when progress bar is shown

### LINKED ISSUE #412: Make background unclickable when progress bar is shown
Currently, all the views on the page are clickable while the progress bar is shown. 

Expected: When the progress bar is shown, make the page just viewable and disable clicks.

working on it.

### PR DESCRIPTION
**Pull request by mejariamol**
- modified progress bar views in all the layouts

fixes #412 

screenshot_2017-08-04-14-42-14

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal please review.

File: app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardFragment.java [hunk 1]
```diff
@@ -143,7 +143,7 @@ private void setupRefreshListener() {
 
     @Override
     public void showProgress(boolean show) {
-        ViewUtils.showView(binding.progressBar, show);
+        ViewUtils.showView(binding.progressView, show);
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardFragment.java]: Is it necessary to rename this? It is a progress bar after all. Also, we can create a common layout and just import it in each one

**Comment by mejariamol** [comment]
@iamareebjamal please review

File: app/src/main/res/layout/sign_up_fragment.xml [hunk 2]
```diff
@@ -11,113 +11,117 @@
             type="org.fossasia.openevent.app.common.data.models.User" />
     </data>
 
-    <android.support.v4.widget.NestedScrollView
+    <FrameLayout
```
Comment (iamareebjamal) [inline app/src/main/res/layout/sign_up_fragment.xml]: Why is this wrapping needed?

Comment (mejariamol) [inline app/src/main/res/layout/sign_up_fragment.xml]: Data binding only allows one data and one layout item

Comment (iamareebjamal) [inline app/src/main/res/layout/sign_up_fragment.xml]: Wrapping in FrameLayout makes no change in data or layout count.

Comment (iamareebjamal) [inline app/src/main/res/layout/sign_up_fragment.xml]: OK, I see what you are saying. But why wrap this in RelativeLayout? 

1. Use CoordinatorLayout as root
2. Do not use RelativeLayout. The layout can be directly imported without needing to be wrapped with any layout

Comment (mejariamol) [inline app/src/main/res/layout/sign_up_fragment.xml]: >Do not use RelativeLayout. The layout can be directly imported without needing to be wrapped with any layout

directly using include was allowing directly binding it for setting visibility by setting id to it.

Comment (iamareebjamal) [inline app/src/main/res/layout/sign_up_fragment.xml]: Still that is better because this method is wrapping it inside an unnecessary hierarchy, which is also bad for performance

Comment (mejariamol) [inline app/src/main/res/layout/sign_up_fragment.xml]: @iamareebjamal please check my updated comment.

Comment (iamareebjamal) [inline app/src/main/res/layout/sign_up_fragment.xml]: https://stackoverflow.com/questions/17653642/hide-included-layout-in-android

Comment (mejariamol) [inline app/src/main/res/layout/sign_up_fragment.xml]: Using data binding it is not allowing? I will re check again. @iamareebjamal

Comment (mejariamol) [inline app/src/main/res/layout/sign_up_fragment.xml]: @iamareebjamal using data binding to set the visibility of the included view directly is not working. Will have to go with this. Same is used for the empty layout too.

Comment (iamareebjamal) [inline app/src/main/res/layout/sign_up_fragment.xml]: Then use CoordinatorLayout instead of FrameLayout

**Comment by mejariamol** [comment]
@iamareebjamal please review now.

File: app/src/main/res/layout/activity_chart.xml [hunk 3]
```diff
@@ -20,19 +20,12 @@
         app:srcCompat="@drawable/ic_exit_full_screen"
         app:fabSize="normal" />
 
-    <LinearLayout
-        android:id="@+id/progressView"
+    <RelativeLayout
```
Comment (iamareebjamal) [inline app/src/main/res/layout/activity_chart.xml]: This can be FrameLayout. No need of RelativeLayout here, RelativeLayout is expensive

File: app/src/main/res/layout/fragment_attendees.xml [hunk 4]
```diff
@@ -56,13 +56,13 @@
...
             android:id="@+id/progressBar"
-            style="?android:attr/progressBarStyle"
             android:layout_width="match_parent"
-            android:layout_height="wrap_content"
-            android:layout_gravity="center"
-            android:visibility="gone"
-            tools:visibility="visible" />
+            android:layout_height="match_parent"
+            android:visibility="gone">
+        <include layout="@layout/progressbar_layout" />
```
Comment (iamareebjamal) [inline app/src/main/res/layout/fragment_attendees.xml]: Indentation is wrong

**Comment by mejariamol** [comment]
@iamareebjamal please review.
