### PR TITLE
fix: Signup and forgot password app crash

### LINKED ISSUE #1135: App crashing on Sign Up and Forgot Password
### Bug Report    

**Actual Behaviour**
App is crashing when we go to the sign up screen , enter the credentials and press the sign up button.

**LogCat for the issue**
``` 
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.fossasia.openevent.app.data.auth.model.Login.setEmail(java.lang.String)' on a null object reference
```        

**Android version and Phone Model**
Lollipop and Xiaomi redmi note 3

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by sridharjajoo**
Fixes #1135 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: App isn't crashing anymore

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java [hunk 1]
```diff
@@ -66,6 +65,7 @@ public void onStart() {
         loginFragmentViewModel.getLogin().observe(this, login -> {
             binding.setLogin(login);
         });
+        sharedViewModel.getEmail().observe(this, email -> binding.getLogin().setEmail(email));
```
Comment (srv-twry) [inline app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java]: I will suggest moving it after line 66 inside the callback if possible. We should only call this once we are sure that the  `login` variable is set on the binding.
