### PR TITLE
fix: Validate Create FAQ question and answer fields for just spaces without text

### LINKED ISSUE #1468: Create FAQ allows blank spaces in question and answer fields making them empty
**Describe the bug**
Even a single space can be entered in the Create FAQ fields and it will be accepted.

**To Reproduce**
1. Go to FAQ
2. Click on the FAB to create a new question and answer set.
3. Enter one or more spaces in the question or answer field and try to submit.
4. It will be accepted.

**Expected behavior**
The spaces should be trimmed and error message should be displayed disallowing empty fields.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1468 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 

After this change, submission will display error if user enters just spaces without any text in the question and answer fields of Create FAQ.

### CODE REVIEW

File: app/src/main/java/com/eventyay/organizer/core/faq/create/CreateFaqFragment.java [hunk 1]
```diff
@@ -44,6 +44,9 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
         validator = new Validator(binding.form);
 
         binding.submit.setOnClickListener(view -> {
+            binding.form.faqQuestion.setText(binding.form.faqQuestion.getText().toString().trim());
+            binding.form.faqAnswer.setText(binding.form.faqAnswer.getText().toString().trim());
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/faq/create/CreateFaqFragment.java]: Just trim in createFaq method

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/faq/create/CreateFaqFragment.java]: I think that it can't be done in the ViewModel since validation is being done through the fragment.
