### PR TITLE
Fixes progressbar on event detail page

### LINKED ISSUE #194: Progressbar doesn't show up on event detail page
Progress bar doesn't show up on event detail page while data is still loading

Expected: Progress bar must be shown until page is loaded with complete data.

### PR DESCRIPTION
**Pull request by mejariamol**
fixes #194

There are two async calls on event detail page. hence progressbar was getting hidden by one of them while other is in progress.

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal @rohanagarwal94 @Shailesh351 @Ronak-59 @mahikaw please review

File: app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java [hunk 1]
```diff
@@ -143,6 +162,10 @@ private void processAttendeesAndDisplay(List<Attendee> attendees) {
 
                 if(event != null)
                     event.checkedIn.set(checkedInAttendees);
+
+                progress ++;
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java]: This code block is repeating, please create function for these 3 lines

File: app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java [hunk 2]
```diff
@@ -130,7 +130,6 @@ public void shouldShowEventError() {
         inOrder.verify(eventDetailView).showProgressBar(true);
         inOrder.verify(eventRepository).getEvent(id, false);
         inOrder.verify(eventDetailView).showEventLoadError(error);
-        inOrder.verify(eventDetailView).showProgressBar(false);
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: You just deleted a test for hiding the progress bar. Now anyone can remove the hiding code and be done with it because the tests will not fail. Please add a test which ensures that if someone forgets to hide the progress bar, it will fail and test it by forgetting to hide the progress bar and confirming that it fails

Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: Test should test app's behavior not what developer has coded. I will add test to check if progressbar gets hidden when complete data gets loaded. :+1:

Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: That is exactly what I was implying

Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: @iamareebjamal done :+1: please review

File: app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java [hunk 3]
```diff
@@ -192,4 +190,23 @@ public void shouldNotAccessView() {
...
+
+        when(eventRepository.getEvent(id, false))
+            .thenReturn(Observable.just(event));
+
+        InOrder inOrder = Mockito.inOrder(eventRepository, eventDetailView);
+
+        eventDetailPresenter.loadAttendees(id, false);
+        eventDetailPresenter.loadTickets(id, false);
+
+        while(eventDetailPresenter.getProgress() < 2) {
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: This is not the correct way to write the test. Load both the attendees and you should not know that the progress should be less than 2 and I have to wait it it becomes so. Besides, all the work is synchronous in threads, so it should work after removing this

File: app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java (hunk 2 above)
Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: @iamareebjamal please check now.

File: app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java [hunk 4]
```diff
@@ -192,4 +192,19 @@ public void shouldNotAccessView() {
...
+
+    @Test
+    public void shouldHideProgressbarCorrectly() {
+        when(eventRepository.getAttendees(id, false))
+            .thenReturn(Observable.fromIterable(attendees));
+
+        when(eventRepository.getEvent(id, false))
+            .thenReturn(Observable.just(event));
+
+        InOrder inOrder = Mockito.inOrder(eventRepository, eventDetailView);
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: There's no transaction with eventRepository, so please remove it from in order, and move the progress bar showing hiding to single test and remove the show code from above two tests

File: app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java [hunk 5]
```diff
@@ -192,4 +191,18 @@ public void shouldNotAccessView() {
...
+        when(eventRepository.getAttendees(id, false))
+            .thenReturn(Observable.fromIterable(attendees));
+
+        when(eventRepository.getEvent(id, false))
+            .thenReturn(Observable.just(event));
+
+        eventDetailPresenter.start();
+
+        assertTrue(eventDetailPresenter.getProgress() >= 2);
+        verify(eventDetailView).showProgressBar(false);
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: Move the progress bar showing hiding to single test and remove the show code from above two tests

Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: I have did the same. I guess. :)

Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: This is only verifying that the progress bar was hidden. And the shown test is in two separate tests. I  was talking about moving the show and hide test in single one and remove the show test from those two

Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: please check now. @iamareebjamal

**Comment by iamareebjamal** [comment]
@arp95 @mahikaw @Shailesh351 @rohanagarwal94 @shreyasnbhat Please review

**Comment by arp95** [comment]
@iamareebjamal @mejariamol
cant we something similar to open event android app? i mean showing percentage of downloads as well?

**Comment by iamareebjamal** [comment]
@arp95 This is for organizers. Don't think they'll mean anything to clients

File: app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java [hunk 6]
```diff
@@ -192,4 +190,22 @@ public void shouldNotAccessView() {
...
+        when(eventRepository.getEvent(id, false))
+            .thenReturn(Observable.just(event));
+
+        InOrder inOrder = Mockito.inOrder(eventDetailView);
+
+        eventDetailPresenter.start();
+
+        assertTrue(eventDetailPresenter.getProgress() >= 2);
+
+        inOrder.verify(eventDetailView, atLeast(2)).showProgressBar(true);
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: At least once please. 2 is a side effect of our implementation. If it is improved, we'll only be showing it once.

Comment (mejariamol) [inline app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java]: True :+1:
