### PR TITLE
fix: put a check on country string and locale object 

### LINKED ISSUE #1156: IllegalArgumentException: Unsupported ISO 3166 country
### Bug Report    

**Actual Behaviour**

Multiple exceptions are thrown on opening create event activity similar to following.
 `IllegalArgumentException: Unsupported ISO 3166 country`

**Steps to reproduce it**
Click on create event FAB.

**LogCat for the issue**

`D/CurrencyUtils: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: es
                     at java.util.Currency.getInstance(Currency.java:140)
                     at org.fossasia.openevent.app.utils.CurrencyUtils.getCountryCurrencyMap(CurrencyUtils.java:75)
                     at org.fossasia.openevent.app.core.event.create.CreateEventPresenter.<init>(CreateEventPresenter.java:56)
                     at org.fossasia.openevent.app.core.event.create.CreateEventPresenter_Factory.get(CreateEventPresenter_Factory.java:29)
                     at org.fossasia.openevent.app.core.event.create.CreateEventPresenter_Factory.get(CreateEventPresenter_Factory.java:10)
                     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                     at org.fossasia.openevent.app.common.mvp.view.BaseFragment.getPresenter(BaseFragment.java:31)
                     at org.fossasia.openevent.app.core.event.create.CreateEventFragment.onStart(CreateEventFragment.java:150)
                     at android.support.v4.app.Fragment.performStart(Fragment.java:2369)
                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                     at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
                     at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3210)
                     at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1270)
                     at android.app.Activity.performStart(Activity.java:6689)
                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:154)
                     at android.app.ActivityThread.main(ActivityThread.java:6123)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Android version and Phone Model**

Nougat and Moto G4 Plus

### PR DESCRIPTION
**Pull request by HHimanshusahni**
Fixes #1156 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes:
When country   is  empty string  or when locale object is having  numeric digits is passed in Currency.getInstance() gives IllegalArguementException  , by  using Timber.d(e) it is shown in the logs.
To overcome this I have used  appropriate checks

### CODE REVIEW

**Comment by iamareebjamal** [comment]
What's the logic of this change

**Comment by HHimanshusahni** [comment]
Currency.getInstance(locale) method will throw IllegalArgumentException:
saying  IllegalArgumentException: Unsupported ISO 3166 
when 
locale.getDisplayCountry() when returns the empty string "" or it returns the  string with numeric digits to String Country.

So I have performed the checks 

 **if( !country.equals("")&&!locale.toString().matches(".*\\d+.*"))**
This if statement is having regex expression which ensures that Currency.getInstance(locale) will called when the above condition are met.

**Comment by iamareebjamal** [comment]
Use Utils.isEmpty instead and fix the title of the PR. Take a look at previously merged PRs

File: app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java [hunk 1]
```diff
@@ -72,12 +72,16 @@ public CurrencyUtils() {
         countryCurrencyMap = new TreeMap<>();
         for (Locale locale : Locale.getAvailableLocales()) {
             try {
-                Currency currency = Currency.getInstance(locale);
                 String country = locale.getDisplayCountry();
-                if (currency != null && country != null && !country.equals("")) {
+                Currency currency = null;
+                if( !Utils.isEmpty(country)&&!locale.toString().matches(".*\\d+.*"))
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: Fix spaces around symbols

File: app/src/main/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java [hunk 2]
```diff
@@ -109,7 +109,7 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
 
         setHasOptionsMenu(true);
 
-        binding.form.eventOriginalImageLayout.setOnClickListener(view -> {
+        binding.form.eventOriginalImage.setOnClickListener(view -> {
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java]: Unnecessary change

File: app/build.gradle [hunk 3]
```diff
@@ -212,7 +212,7 @@ dependencies {
     testAnnotationProcessor "org.projectlombok:lombok:${versions.lombok}"
 
     //colorpicker
-    implementation 'com.pes.materialcolorpicker:library:1.2.4'
+    implementation 'com.pes.materialcolorpicker:library:1.2.5'
```
Comment (iamareebjamal) [inline app/build.gradle]: Unnecessary change

File: app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java [hunk 4]
```diff
@@ -72,12 +72,16 @@ public CurrencyUtils() {
...
+                    currency = Currency.getInstance(locale);
+                if (currency != null && country != null) {
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: Why removed the empty check?

File: app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java [hunk 5]
```diff
@@ -72,12 +72,16 @@ public CurrencyUtils() {
...
                     countryCurrencyMap.put(country, currency.toString());
+
                 }
             } catch (IllegalArgumentException e) {
+
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: Unnecessary

File: app/src/main/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java (hunk 2 above)
Comment (HHimanshusahni) [reply app/src/main/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java]: Sorry sir , this was the change from the another pull request I have made whose commits got mixed with it .I will fix it

File: app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java (hunk 4 above)
Comment (HHimanshusahni) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: https://github.com/fossasia/open-event-orga-app/pull/1440#issuecomment-454515293 
it works the same as you mentioned

File: app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java (hunk 1 above)
Comment (HHimanshusahni) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: fixed

File: app/build.gradle (hunk 3 above)
Comment (HHimanshusahni) [reply app/build.gradle]: reverted back

File: app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java (hunk 5 above)
Comment (HHimanshusahni) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: fixed

File: app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java (hunk 4 above)
Comment (HHimanshusahni) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: Sir as you mentioned in the above comment https://github.com/fossasia/open-event-orga-app/pull/1440#issuecomment-454515293 
**Use Utils.isEmpty instead** 
that's why , I have replaced it with Utils.isEmtpy() method

Comment (iamareebjamal) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: You're not looking at the line I have commented on

Comment (iamareebjamal) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: You're not able to look at line 80 and I don't know what to do with this PR now

Comment (HHimanshusahni) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: **if (currency != null && country != null)** are talking about this line please explain what is the problem ? Should I use Utils.isEmpty() method to check whether country string is null? Please clarify ? 
Or you mean that Exception handling used here is Unnecessary now ?
(Please help It is my second pull  request and I am new to Open source and github)

Comment (iamareebjamal) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: Look at what it was before you changed it and yes, that is the line I commented on

Comment (HHimanshusahni) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: It was like that before https://github.com/fossasia/open-event-orga-app/blob/b2e22595e5ebe8bc1edd36ea23abe3d1cd495bc4/app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java#L77
I just moved the check  !**country.equals("")** .
So should I use !Utils.isEmpty(country) instead instead of currency != null ?

Comment (iamareebjamal) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: Yes

File: app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java [hunk 6]
```diff
@@ -72,9 +72,12 @@ public CurrencyUtils() {
         countryCurrencyMap = new TreeMap<>();
         for (Locale locale : Locale.getAvailableLocales()) {
             try {
-                Currency currency = Currency.getInstance(locale);
                 String country = locale.getDisplayCountry();
-                if (currency != null && country != null && !country.equals("")) {
+                Currency currency = null;
+                if (!country.equals("") && !locale.toString().matches(".*\\d+.*")) {
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: Use Utils.isEmpty

File: app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java [hunk 7]
```diff
@@ -72,9 +72,12 @@ public CurrencyUtils() {
         countryCurrencyMap = new TreeMap<>();
         for (Locale locale : Locale.getAvailableLocales()) {
             try {
-                Currency currency = Currency.getInstance(locale);
                 String country = locale.getDisplayCountry();
-                if (currency != null && country != null && !country.equals("")) {
+                Currency currency = null;
+                if (!Utils.isEmpty(country) && !country.equals("") && !locale.toString().matches(".*\\d+.*")) {
```
[the remark this answers is not in the document]
Comment (iamareebjamal) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: `!country.equals("")` - redundant

[the remark this answers is not in the document]
Comment (HHimanshusahni) [reply app/src/main/java/com/eventyay/organizer/utils/CurrencyUtils.java]: https://github.com/fossasia/open-event-orga-app/pull/1440#discussion_r248358301 that is why I have removed it earlier
